version: '2'
linters:
  default: all
  disable:
    - nlreturn # wsl_v5 is good enough.
    - depguard # not very useful.
    - exhaustruct # deprecated
    - wsl # deprecated
    - gomodguard # deprecated
    # too noisy for a binary format parser
    - mnd
    - varnamelen
    - exhaustruct_v5

  settings:
    gosec:
      excludes:
        - G304
        - G115
        - G602
        - G705
    gocritic:
      enable-all: true
      settings:
        unnamedResult:
          checkExported: true
    errcheck:
      check-type-assertions: true
      check-blank: false
      disable-default-exclusions: false
      exclude-functions:
        - (*os.File).Close
        - (io.Closer).Close

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
